@baseUrl = http://localhost:5000
@urlPath = api/v1

###
POST {{baseUrl}}/{{urlPath}}/contact
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "name": "gucio hujek",
  "email": "dvds1987@gmail.com",
  "message": "siema mordo"
}
